build:
  script: 
    - dotnet build ./src/SimplyTyped.Core/SimplyTyped.Core.csproj
    - dotnet build ./src/SimplyTyped/SimplyTyped.csproj
  image: microsoft/dotnet:sdk
  stage: build

test:
  script: dotnet test ./test/*
  image: microsoft/dotnet:sdk
  stage: test

deploy:
  stage: deploy
  image: microsoft/dotnet:sdk
  script:  
    - dotnet pack ./src/SimplyTyped.Core/SimplyTyped.Core.csproj -o ./ -c Release /p:PackageVersion=$CI_COMMIT_TAG
    - dotnet pack ./src/SimplyTyped/SimplyTyped.csproj -o ./ -c Release /p:PackageVersion=$CI_COMMIT_TAG
    - PACKAGES=$(ls ./src/**/*.nupkg)
    - dotnet nuget push $PACKAGES -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY -v $CI_COMMIT_TAG
  only:
    - tags